version: "3.7"

services:
  api:
    restart: always
    build:
        context: .
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
