version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 30068:3000
    command: yarn start:dev
    depends_on:
      - mongodb
    env_file:
      - ./.env

  mongodb:
    image: mongo:4.4.6
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env.db

volumes:
  mongo_data:
