version: '3.7'

services:
  api:
    restart: always
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo:4.4.6
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env.db

volumes:
  mongo_data:
